#!/bin/bash
echo "clean"
set -x
rm -rf out chat.jar
echo "setup"
mkdir out
cp lib/Java-WebSocket-1.3.8.jar out
cp src/* out
cd out
unzip Java-WebSocket-1.3.8.jar
echo "Main-Class: MultiChat" > mf.txt
echo "compile"
javac -encoding UTF8 *.java
echo "post-clean"
rm *.java
rm *.jar
echo "package"
jar cfe ../chat.jar Launcher *
cd ..
echo "run"
java -jar chat.jar &
